# HARL-based Innovation 1 Validation Configuration
# 基于HARL框架的创新点一验证配置

# Environment Configuration
num_agents: 5
num_rsus: 2
map_size: 1000.0
max_episodes: 1000
max_steps: 200
state_type: "EP"  # 状态类型: "EP" (每个智能体) 或 "FP" (全局状态)

# HASAC Algorithm Configuration
lr: 0.0003
polyak: 0.995
alpha: 0.2
gamma: 0.99
batch_size: 32
buffer_size: 100000
start_steps: 5000
update_after: 1000
update_every: 50

# Transformer Configuration (Innovation 1)
use_transformer: true
max_seq_length: 50
transformer_d_model: 256
transformer_nhead: 8
transformer_num_layers: 4
transformer_dim_feedforward: 512
transformer_dropout: 0.1

# Contrastive Learning Configuration (Innovation 1)
use_contrastive_learning: true
contrastive_temperature: 0.1
similarity_threshold: 0.8
temporal_weight: 0.1
contrastive_loss_weight: 0.1

# Network Architecture
hidden_size: 256
activation: "relu"
final_activation: "identity"

# Validation Settings
evaluation_frequency: 50
save_best_model: true
tensorboard_logging: true

# Device Configuration
device: "auto"  # "auto", "cpu", or "cuda" 