# RoPE增强的Transformer配置

# 基本Transformer参数
transformer_d_model: 256        # Transformer模型的维度
transformer_nhead: 8            # 多头注意力中的头数
transformer_num_layers: 4       # Transformer编码器层数
transformer_dim_feedforward: 512 # 前馈网络的维度
transformer_dropout: 0.1        # Dropout率
max_seq_length: 100             # 最大序列长度

# RoPE相关配置
use_rope: true                  # 是否使用RoPE (Rotary Position Encoding)
rope_base: 10000.0              # RoPE的频率基数，控制旋转速度
rope_scale_base: null           # RoPE缩放基数，用于处理超长序列，默认不使用

# 对比学习配置
use_contrastive_learning: true  # 是否使用对比学习
contrastive_temperature: 0.1    # 对比学习温度参数
similarity_threshold: 0.8       # 相似性阈值
temporal_weight: 0.1            # 时间权重 